export enum SessionState {
  WAITING_DOCUMENT_TYPE = 'WAITING_DOCUMENT_TYPE',
  WAITING_DOCUMENT_NUMBER = 'WAITING_DOCUMENT_NUMBER',
  WAITING_MFA_VERIFICATION = 'WAITING_MFA_VERIFICATION',
  AUTHENTICATED = 'AUTHENTICATED',
  SHOWING_MENU = 'SHOWING_MENU',
  BLOCKED = 'BLOCKED',
  RATE_LIMITED = 'RATE_LIMITED'
} 